development:
  sessions:
    default:
      database: datadb
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: datadb
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      database: datadb
      hosts:
        - localhost:27017
